"""Initial Migrations

Revision ID: a8dcd9d0f467
Revises: 
Create Date: 2023-08-03 00:09:00.184693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8dcd9d0f467'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('participants',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('institute', sa.String(length=30), nullable=True),
    sa.Column('phone', sa.String(length=10), nullable=False),
    sa.Column('email', sa.String(length=15), nullable=False),
    sa.Column('applied', sa.String(length=35), nullable=False),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('Id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('participants')
    # ### end Alembic commands ###
